<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2OU9P92" name="Test" tests="2" failures="1" timestamp="21 Jul 2020 14:20:41 GMT" time="299.19" errors="0">
  <testcase name="Tc_Login_001" time="0.982" classname="com.Automation.HoroLab.TestCases.Login"/>
  <testcase name="Tc_Login_002" time="31.072" classname="com.Automation.HoroLab.TestCases.Login">
    <failure type="java.lang.AssertionError" message="Fail due to exception Expected condition failed: waiting for visibility of element located by By.xpath: //*[text()=&amp;apos;Login Failed, Reason : Bad credentials&amp;apos;] (tried for 30 second(s) with 500 MILLISECONDS interval)">
      <![CDATA[java.lang.AssertionError: Fail due to exception Expected condition failed: waiting for visibility of element located by By.xpath: //*[text()='Login Failed, Reason : Bad credentials'] (tried for 30 second(s) with 500 MILLISECONDS interval)
	at com.Automation.HoroLab.Modules.LoginPage.validateLoginErrorMsg(LoginPage.java:75)
	at com.Automation.HoroLab.TestCases.Login.Tc_Login_002(Login.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Tc_Login_002 -->
</testsuite> <!-- Test -->
